
S2H = SimpleRequest
H2S = SimpleIndication
BSVFILES = Top.bsv Simple.bsv ../JenkinsHash.bsv ../../../lib/SerDes.bsv
CPPFILES = testsimple.cpp ../jenkins_sw/jenkins_hash.c
NUMBER_OF_MASTERS = 0

CONNECTALDIR=/home/shuotao/tools/xbsv
include $(CONNECTALDIR)/Makefile.connectal



